### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Geekince** [vorgoron/Multilang-Keyboard#1]
Hi,i want to change your package name,but l'm worry about if it will affect the armeabi.jar.Do they have a connection？

**Comment by vorgoron** [comment]
Hi, if you want to change package name, you may change only 'extrainputmethod' package (package 'com/android/inputmethod' unable to change). You may see how it made on 'dev' branch

**Comment by wangjinyu501** [comment]
Thank you.
